version: '3'

services:
  web:
    build: .
    container_name: react_nginx
    ports:
      - "80:80"
  
  dev:
    build:
      context: .
      target: build  # This uses the build stage from your Dockerfile
    container_name: react_dev
    ports:
      - "5174:5174"
    volumes:
      - ./:/app  # Mount your code into the container
      - /app/node_modules  # Keep node_modules from the container
    command: npm run dev  # or whatever your development script is